### ISSUE TITLE
Override on user input

### ISSUE THREAD

**Issue by SethuSenthil** [Ashish-Raturi/scroll_loop_auto_scroll#1]
It would be fantastic if there were an option to respond to user input so the user can still scroll around (if the child element is some scrollable). 
If the user attempts to scroll it will respond to their gesture as a normal scrollable widget and then start the auto-scrolling immediately, or a parameter with a set delay to start the animation again after user interference. \

**Comment by Ashish-Raturi** [comment]
Good idea. I will create it soon.

**Comment by Ashish-Raturi** [comment]
Done, use scroll_loop_auto_scroll: ^0.0.5

**Comment by SethuSenthil** [comment]
Awesome! This is exactly how I imagined how this feature would be!

**Comment by Ashish-Raturi** [comment]
@Ashish-Raturi thanks men

**Comment by oliveyew** [comment]
@Ashish-Raturi  thanks men

**Comment by oliveyew** [comment]
@SethuSenthil hi

**Comment by oliveyew** [comment]
nice

**Comment by oliveyew** [comment]
nice
