### ISSUE TITLE
Duration parameter not being respected in 0.0.5

### ISSUE THREAD

**Issue by SethuSenthil** [Ashish-Raturi/scroll_loop_auto_scroll#2]
There seems to be a bug in the latest release which is not present in the previous release where the custom duration parameter is not being set, instead, it just defaults to a duration of 1 second regardless of what is overridden.

**Comment by Ashish-Raturi** [comment]
Which one you are talking about. I Just removed **pause & disableAnimation**. 
Can you explain more.

Previous release params
<img width="838" alt="Screenshot 2022-05-26 at 7 55 29 AM" src="https://user-images.githubusercontent.com/50191855/170402889-df344f93-b1f1-46e3-8743-4af60decd607.png">

Latest release params
<img width="668" alt="Screenshot 2022-05-25 at 1 14 07 PM" src="https://user-images.githubusercontent.com/50191855/170208685-068b7ee4-eb11-4012-871d-c8a893eaed71.png">

**Comment by Ashish-Raturi** [comment]
Hey men, it would be best if you gave me a reply. Else, I will close this issue.

**Comment by matteoberla** [comment]
same error here, no matter which duration i set, it always keeps scroll very fast 


```
ScrollLoopAutoScroll(
                  delay: Duration(seconds: 1),
                  duration: Duration(seconds: 50),
                  gap: 25,
                  scrollDirection: Axis.vertical,
                  child: ListView.builder(
                    shrinkWrap: true,
                    itemCount:
                        10,
                    itemBuilder: (context, index) {
                      return MyChild(index);
                    },
                  ),
                )
```
